sudo: required

language: bash

services:
  - docker

before_install:
  - make prepare

script:
  - make build
  - make test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make push
